apiVersion: apps/v1
kind: Deployment 
metadata: 
  name: nodeapp-deployment
  labels: 
    app: nodeapp #the deployement will have this name
spec: 
  replicas: 1
  selector: 
    matchLabels:
      app: nodeapp
  template: 
    metadata:
      labels:
        app: nodeapp
    spec:
      serviceAccountName: nodeapp
      automountServiceAccountToken: false  
      containers:
      - name: nodeserver
        image: yessminemallek/nodeapp:latest
        resources:
          limits:
            memory: "512Mi"  
            cpu: "500m"       
        ports:
        - containerPort: 3001 #Our docker image is exposed on 3000
        
      
     
  