apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeapp-deployment
  labels:
    app: nodeapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodeapp
  template:
    metadata:
      labels:
        app: nodeapp 
    spec:
      seserviceAccountName: nodeapp
      automountServiceAccountToken: false 
      containers:
      - name: nodeserver
        resources:
          limits:
            memory: "512Mi"  
            cpu: "500m"
        image: yessminemallek/nodeapp:latest
        ports:
        - containerPort: 3001
        
        
---

apiVersion: v1
kind: Service
metadata:
  name: nodeapp-service
spec:
  selector:
    app: nodeapp 
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 3001
    targetPort: 3001
    nodePort: 31110